### ISSUE TITLE
demo (https://blog.miraclemilk.me/Seje2) page layout broken

### ISSUE THREAD

**Issue by ghost** [eatradish/Seje2#1]
This is a really elegant blog theme, but the demo page layout broken:

<img width="928" alt="image" src="https://user-images.githubusercontent.com/45538642/201180300-a786daf2-c6eb-46dd-ace4-5d12ab117ba0.png">

I test on chrome and firefox and they show the same wired layout.

**Comment by eatradish** [comment]
啊之前一直没看前，对不起。

之前尝试修过这个问题，原因是不知道为什么 zola 不吃 Seje2 的根目录配置，主题本身是好的

**Comment by eatradish** [comment]
现在正常了
