### ISSUE TITLE
Fix Chinese Date Layout

### ISSUE THREAD

**Issue by criphc** [eatradish/Seje2#2]
The Chinese dates are shown as "二 〇 二 二 年九月十七日" which have these weird spaces, I would recommend fix it by hard-code it in /templates/macro.html like this:
```html
{% macro format_chinese_date(year, month, day) %}
{% set lut1 = [
    '二〇二〇', '二〇二一', '二〇二二', '二〇二三', '二〇二四', '二〇二五', '二〇二六', '二〇二七', '二〇二八', '二〇二九', 
    '二〇三〇', '二〇三一', '二〇三二', '二〇三三', '二〇三四', '二〇三五', '二〇三六', '二〇三七', '二〇三八', '二〇三九', 
    '二〇四〇', '二〇四一', '二〇四二', '二〇四三', '二〇四四', '二〇四五', '二〇四六', '二〇四七', '二〇四八', '二〇四九', 
    '二〇五〇', '二〇五一', '二〇五二', '二〇五三', '二〇五四', '二〇五五', '二〇五六', '二〇五七', '二〇五八', '二〇五九', 
    '二〇六〇', '二〇六一', '二〇六二', '二〇六三', '二〇六四', '二〇六五', '二〇六六', '二〇六七', '二〇六八', '二〇六九', 
    '二〇七〇', '二〇七一', '二〇七二', '二〇七三', '二〇七四', '二〇七五', '二〇七六', '二〇七七', '二〇七八', '二〇七九', 
    '二〇八〇', '二〇八一', '二〇八二', '二〇八三', '二〇八四', '二〇八五', '二〇八六', '二〇八七', '二〇八八', '二〇八九', 
    '二〇九〇', '二〇九一', '二〇九二', '二〇九三', '二〇九四', '二〇九五', '二〇九六', '二〇九七', '二〇九八', '二〇九九'] %}
{% set lut2 = ["一", "二", "三", "四", "五", "六", "七", "八", "九", "十", "十一", "十二"] %}
{% set lut3 = [
    '一日', '二日', '三日', '四日',
    '五日', '六日', '七日', '八日',
    '九日', '十日', '十一', '十二',
    '十三', '十四', '十五', '十六',
    '十七', '十八', '十九', '二十',
    '廿一', '廿二', '廿三', '廿四',
    '廿五', '廿六', '廿七', '廿八',
    '廿九', '三十', '卅一'] %}
{{ lut1 | nth(n=year-2020)}}年{{ lut2 | nth(n=month-1)}}月{{ lut3 | nth(n=day-1) }}
{% endmacro %}
``` 
_(Thanks to ChatGPT, I done it in just seconds)_
And this will work till 2100, by when we would probably have been dead. 
_(I also made a little tweak on how days are shown, as a personal preference.)_

**Comment by eatradish** [comment]
感谢 issue！

这个问题我也困扰了很久………因为行为会随着浏览器的变化而变化，比如说 Firefox 中，行为就是对的：

![image](https://user-images.githubusercontent.com/19554922/230278083-24d8b4ff-dbbd-4f03-9687-d1bfad92dcff.png)

而在 Chrome 中就变成了这样：

![image](https://user-images.githubusercontent.com/19554922/230278208-6d5bc95b-99dd-458a-8d6f-16aa71fa7b10.png)

因此我更倾向于解决方案应该是看看为什么 Chrome 和 Firefox 有着不同的行为，针对这些行为尝试进行改进

最近因为在忙着点别的项目，再加上我对这些网页技术的理解十分有限，于是就一直搁置（另一个问题是中文的字体 fallback 也有小问题）

**Comment by criphc** [comment]
I am using Safari 16.4, it's the same as Chrome, just fyi.

**Comment by eatradish** [comment]
问题已修复于 3426d73
