### ISSUE TITLE
Fix license info in footer

### ISSUE THREAD

**Issue by criphc** [eatradish/Seje2#3]
in /tamplates/base.html, line 69, add ".extra":
`<p class="license">{{ config.extra.license | default(value='') }}</p>`
in /config.toml, under `[extra]`, write:
 `license = "© Criphc, 2023" # For example`

And it works perfectly:
<img width="828" alt="image" src="https://user-images.githubusercontent.com/27053399/230290219-72bb647e-cbe2-4551-8440-75fb4078103d.png">

**Comment by eatradish** [comment]
请问这里的意思是上下没有对齐吗？

**Comment by eatradish** [comment]
多谢 issue！

你开个 PR 我来合并你的修改还是我来修改？

**Comment by criphc** [comment]
您来吧，就两行的事儿（

**Comment by eatradish** [comment]
问题修复于 797487a55f33a37080809398309f59dfa648e694
