### ISSUE TITLE
demo offline?

### ISSUE THREAD

**Issue by Jieiku** [eatradish/Seje2#4]
demo offline?

**Comment by eatradish** [comment]
Domain expired and godaddy's 2fa blocked me from renewing it so ......

**Comment by Jieiku** [comment]
ouch, you could try netlify, its where I host abridge: https://abridge.netlify.app/

It is free.

**Comment by eatradish** [comment]
> ouch, you could try netlify, its where I host abridge: https://abridge.netlify.app/
> 
> It is free.

Done
